# Generated by Django 3.2.9 on 2021-11-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='URL адрес')),
                ('author', models.CharField(max_length=128, verbose_name='Автор')),
                ('votes', models.PositiveBigIntegerField(verbose_name='Голоса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128, verbose_name='Автор')),
                ('message', models.TextField(verbose_name='Коментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news_board.post')),
            ],
        ),
    ]
